[package]
name = "pinger"
version = "0.1.0"
authors = ["Zonda Yang <u226699@gmail.com>"]
description = "pinger library"
homepage = "https://github.com/zondatw/knock_knock"
repository = "https://github.com/zondatw/knock_knock"
edition = "2021"
license = "MIT"

[dependencies]
regex = "1.1.9"